# Adapted from the example on https://github.com/tox-dev/tox-gh

name: test
on:
    push:
    pull_request:

concurrency:
    group: check-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: test with ${{ matrix.py }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                py:
                    - "3.11"
                    - "3.10"
                    - "3.9"
                    - "3.8"
                    - "3.7"
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup python for test ${{ matrix.py }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.py }}
            - name: Install dependencies
              run: python -m pip install -r requirements-tox.txt tox-gh==1.2
            - name: Setup test suite
              run: tox -vv --notest
            - name: Run test suite
              run: tox --skip-pkg-install
